version: 0.2

env:
  variables:
    prod_distribution: EC1JOIYLV0ZB8
phases:
  install:
    commands:
      - npm i
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Pre_build Phase
  build:
    commands:
      - echo Build Phase
      - npm run build:prod
      - DISTRIBUTION=$prod_distribution
  post_build:
    commands:
      - echo PostBuild Phase
      - aws s3 sync ./dist $S3_BUCKET
      - aws cloudfront create-invalidation --distribution-id=$DISTRIBUTION --paths "/*"
